set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN D9 } [get_ports { HSK_UART_txd }]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN C9 } [get_ports { HSK_UART_rxd }]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN C8 } [get_ports { CLK_IIC_scl_io }]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN D8 } [get_ports { CLK_IIC_sda_io }]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN A7 } [get_ports { HSK2_UART_txd }]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN B7 } [get_ports { HSK2_UART_rxd }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AR12 DIFF_TERM TRUE} [get_ports { SYSCLK_P }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AR13 DIFF_TERM TRUE} [get_ports { SYSCLK_N }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN G17 DIFF_TERM TRUE} [get_ports { RXCLK_P[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN F17 DIFF_TERM TRUE} [get_ports { RXCLK_N[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AM10 } [get_ports { TXCLK_P[0]}]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN B15  } [get_ports { TXCLK_P[1]}]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN P16  } [get_ports { TXCLK_P[2]}]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AW10 } [get_ports { TXCLK_P[3]}]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AN10 } [get_ports { TXCLK_N[0]}]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN C15  } [get_ports { TXCLK_N[1]}]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN N16  } [get_ports { TXCLK_N[2]}]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AW11 } [get_ports { TXCLK_N[3]}]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN B13 DIFF_TERM TRUE} [get_ports { CINTIO_P[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN A14 DIFF_TERM TRUE} [get_ports { CINTIO_P[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN BB8 DIFF_TERM TRUE} [get_ports { CINTIO_P[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AN13 DIFF_TERM TRUE} [get_ports { CINTIO_P[3] }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN A12 DIFF_TERM TRUE} [get_ports { CINTIO_N[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN A13 DIFF_TERM TRUE} [get_ports { CINTIO_N[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN BB9 DIFF_TERM TRUE} [get_ports { CINTIO_N[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AM13 DIFF_TERM TRUE} [get_ports { CINTIO_N[3] }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AL15 UNAVAILABLE_DURING_CALIBRATION TRUE} [get_ports { COUT_P[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN A18 } [get_ports { COUT_P[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN C13 } [get_ports { COUT_P[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AY9 } [get_ports { COUT_P[3] }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AM15 } [get_ports { COUT_N[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN B18 } [get_ports { COUT_N[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN D13 } [get_ports { COUT_N[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AW9 UNAVAILABLE_DURING_CALIBRATION TRUE} [get_ports { COUT_N[3] }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN J16 DIFF_TERM TRUE} [get_ports { CINA_P[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN C18 DIFF_TERM TRUE} [get_ports { CINA_P[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN E16 DIFF_TERM TRUE} [get_ports { CINA_P[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN G18 DIFF_TERM TRUE} [get_ports { CINA_P[3] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN G16 DIFF_TERM TRUE} [get_ports { CINA_P[4] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN P15 DIFF_TERM TRUE} [get_ports { CINA_P[5] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN F14 DIFF_TERM TRUE} [get_ports { CINA_P[6] }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN H16 DIFF_TERM TRUE} [get_ports { CINA_N[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN D18 DIFF_TERM TRUE} [get_ports { CINA_N[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN D16 DIFF_TERM TRUE} [get_ports { CINA_N[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN F18 DIFF_TERM TRUE} [get_ports { CINA_N[3] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN F15 DIFF_TERM TRUE} [get_ports { CINA_N[4] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN N15 DIFF_TERM TRUE} [get_ports { CINA_N[5] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN E14 DIFF_TERM TRUE} [get_ports { CINA_N[6] }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN K17 DIFF_TERM TRUE} [get_ports { CINB_P[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN B16 DIFF_TERM TRUE} [get_ports { CINB_P[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN E17 DIFF_TERM TRUE} [get_ports { CINB_P[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN A17 DIFF_TERM TRUE} [get_ports { CINB_P[3] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN J18 DIFF_TERM TRUE} [get_ports { CINB_P[4] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN M15 DIFF_TERM TRUE} [get_ports { CINB_P[5] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN K16 DIFF_TERM TRUE} [get_ports { CINB_P[6] }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN L17 DIFF_TERM TRUE} [get_ports { CINB_N[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN C16 DIFF_TERM TRUE} [get_ports { CINB_N[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN D17 DIFF_TERM TRUE} [get_ports { CINB_N[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN B17 DIFF_TERM TRUE} [get_ports { CINB_N[3] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN H18 DIFF_TERM TRUE} [get_ports { CINB_N[4] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN L15 DIFF_TERM TRUE} [get_ports { CINB_N[5] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN K15 DIFF_TERM TRUE} [get_ports { CINB_N[6] }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AN11 DIFF_TERM TRUE} [get_ports { CINC_P[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AP14 DIFF_TERM TRUE} [get_ports { CINC_P[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AK15 DIFF_TERM TRUE} [get_ports { CINC_P[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AK14 DIFF_TERM TRUE} [get_ports { CINC_P[3] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AR14 DIFF_TERM TRUE} [get_ports { CINC_P[4] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AM14 DIFF_TERM TRUE} [get_ports { CINC_P[5] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AV11 DIFF_TERM TRUE} [get_ports { CINC_P[6] }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AM11 DIFF_TERM TRUE} [get_ports { CINC_N[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AN14 DIFF_TERM TRUE} [get_ports { CINC_N[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AJ15 DIFF_TERM TRUE} [get_ports { CINC_N[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AJ14 DIFF_TERM TRUE} [get_ports { CINC_N[3] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AR15 DIFF_TERM TRUE} [get_ports { CINC_N[4] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AL14 DIFF_TERM TRUE} [get_ports { CINC_N[5] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AU11 DIFF_TERM TRUE} [get_ports { CINC_N[6] }]

# NOTE: These are the non-prototype definitions for CIND. The prototype can't be used for C/D anyway.
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN BA7  DIFF_TERM TRUE} [get_ports { CIND_P[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AY8  DIFF_TERM TRUE} [get_ports { CIND_P[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AR10 DIFF_TERM TRUE} [get_ports { CIND_P[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN BA6  DIFF_TERM TRUE} [get_ports { CIND_P[3] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AV12 DIFF_TERM TRUE} [get_ports { CIND_P[4] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AV8  DIFF_TERM TRUE} [get_ports { CIND_P[5] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AP12 DIFF_TERM TRUE} [get_ports { CIND_P[6] }]

set_property -dict { IOSTANDARD LVDS PACKAGE_PIN BA8  DIFF_TERM TRUE} [get_ports { CIND_N[0] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AW8  DIFF_TERM TRUE} [get_ports { CIND_N[1] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AP10 DIFF_TERM TRUE} [get_ports { CIND_N[2] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN BB6  DIFF_TERM TRUE} [get_ports { CIND_N[3] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AW12 DIFF_TERM TRUE} [get_ports { CIND_N[4] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AV9  DIFF_TERM TRUE} [get_ports { CIND_N[5] }]
set_property -dict { IOSTANDARD LVDS PACKAGE_PIN AN12 DIFF_TERM TRUE} [get_ports { CIND_N[6] }]


set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN D6 } [get_ports { GPIO[0] }]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN F6 } [get_ports { GPIO[1] }]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN G6 } [get_ports { GPIO[2] }]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN D7 } [get_ports { GPIO[3] }]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN E7 } [get_ports { GPIO[4] }]

set_property -dict { PACKAGE_PIN AD12 } [get_ports { MGTCLK_N } ]
set_property -dict { PACKAGE_PIN AD11 } [get_ports { MGTCLK_P } ]
set_property -dict { PACKAGE_PIN AG2 } [get_ports { MGTRX_P[0] }]
set_property -dict { PACKAGE_PIN AG1 } [get_ports { MGTRX_N[0] }]
set_property -dict { PACKAGE_PIN AF4 } [get_ports { MGTRX_P[1] }]
set_property -dict { PACKAGE_PIN AF3 } [get_ports { MGTRX_N[1] }]
set_property -dict { PACKAGE_PIN AE2 } [get_ports { MGTRX_P[2] }]
set_property -dict { PACKAGE_PIN AE1 } [get_ports { MGTRX_N[2] }]
set_property -dict { PACKAGE_PIN AH4 } [get_ports { MGTRX_P[3] }]
set_property -dict { PACKAGE_PIN AH3 } [get_ports { MGTRX_N[3] }]

set_property -dict { PACKAGE_PIN AF8 } [get_ports { MGTTX_P[0] }]
set_property -dict { PACKAGE_PIN AF7 } [get_ports { MGTTX_N[0] }]
set_property -dict { PACKAGE_PIN AE6 } [get_ports { MGTTX_P[1] }]
set_property -dict { PACKAGE_PIN AE5 } [get_ports { MGTTX_N[1] }]
set_property -dict { PACKAGE_PIN AD8 } [get_ports { MGTTX_P[2] }]
set_property -dict { PACKAGE_PIN AD7 } [get_ports { MGTTX_N[2] }]
set_property -dict { PACKAGE_PIN AG6 } [get_ports { MGTTX_P[3] }]
set_property -dict { PACKAGE_PIN AG5 } [get_ports { MGTTX_N[3] }]

set_property -dict { PACKAGE_PIN AR2 } [get_ports { GBE_RX_P[0] }]
set_property -dict { PACKAGE_PIN AR1 } [get_ports { GBE_RX_N[0] }]
set_property -dict { PACKAGE_PIN AP8 } [get_ports { GBE_TX_P[0] }]
set_property -dict { PACKAGE_PIN AP7 } [get_ports { GBE_TX_N[0] }]
set_property -dict { PACKAGE_PIN AT4 } [get_ports { GBE_RX_P[1] }]
set_property -dict { PACKAGE_PIN AT3 } [get_ports { GBE_RX_N[1] }]
set_property -dict { PACKAGE_PIN AR6 } [get_ports { GBE_TX_P[1] }]
set_property -dict { PACKAGE_PIN AR5 } [get_ports { GBE_TX_N[1] }]

#set_property -dict { PACKAGE_PIN AN2 } [get_ports { NC_RX_P[1] }]
#set_property -dict { PACKAGE_PIN AN1 } [get_ports { NC_RX_N[1] }]
#set_property -dict { PACKAGE_PIN AP4 } [get_ports { NC_RX_P[0] }]
#set_property -dict { PACKAGE_PIN AP3 } [get_ports { NC_RX_N[0] }]
#set_property -dict { PACKAGE_PIN AM8 } [get_ports { NC_TX_P[1] }]
#set_property -dict { PACKAGE_PIN AM7 } [get_ports { NC_TX_N[1] }]
#set_property -dict { PACKAGE_PIN AN6 } [get_ports { NC_TX_P[0] }]
#set_property -dict { PACKAGE_PIN AN5 } [get_ports { NC_TX_N[0] }]

set_property -dict { PACKAGE_PIN AH12 } [get_ports { GBE_CLK_P }]
set_property -dict { PACKAGE_PIN AH11 } [get_ports { GBE_CLK_N }]
#set_property -dict { PACKAGE_PIN AG10 } [get_ports { NC_GCLK_P }]
#set_property -dict { PACKAGE_PIN AG9 }  [get_ports { NC_GCLK_N }]

set_property -dict { PACKAGE_PIN AT21 IOSTANDARD LVDS DIFF_TERM TRUE } [ get_ports { DDR_CLK_N[0] }]
set_property -dict { PACKAGE_PIN AT22 IOSTANDARD LVDS DIFF_TERM TRUE } [ get_ports { DDR_CLK_P[0] }]
set_property -dict { PACKAGE_PIN D32  IOSTANDARD LVDS DIFF_TERM TRUE } [ get_ports { DDR_CLK_N[1] }]
set_property -dict { PACKAGE_PIN E32  IOSTANDARD LVDS DIFF_TERM TRUE } [ get_ports { DDR_CLK_P[1] }]

set_property -dict { PACKAGE_PIN B6 IOSTANDARD LVCMOS25 } [ get_ports { LGPIO[0] }]
set_property -dict { PACKAGE_PIN B5 IOSTANDARD LVCMOS25 } [get_ports { LGPIO[1] }]

# these do not matter

